#ifndef CONSTANT_H
#define CONSTANT_H

// Typedef
typedef unsigned int p_uint;

// Screen
#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

// Keyboard
#define NUMBER_OF_KEYS 2

#define KEY_CODE_1 SDLK_ESCAPE
#define KEY_CODE_2 SDLK_RETURN

// Game content
#define HOUSING_FOOD_NEEDS 10

#define HOUSE_MAX_INHAB 1
#define HOUSE_WATER_NEEDS 10
#define HOUSE_ENERGY_NEEDS 10

#define LOW_ENERGY_HOUSE_WATER_NEEDS 10
#define LOW_ENERGY_HOUSE_ENERGY_NEEDS 10

#define BUILDING_MAX_INHAB_PER_FLOOR 1
#define BUILDING_WATER_NEEDS 10
#define BUILDING_ENERGY_NEEDS 10
#define BUILDING_FLOOR 2
#define BUILDING_MAX_FLOOR 5

#define LOW_ENERGY_BUILDING_WATER_NEEDS 10
#define LOW_ENERGY_BUILDING_ENERGY_NEEDS 10

#endif // !CONSTANT_H